attn_positional_bias: rope
attn_positional_bias_n_spatial: 16
augment: 3
batch_size: 8
cache: false
cachedir: .cache
causal_norm: quiet_softmax
compress: false
config: /root/vast/mustafa/trackastra/scripts/leaveout-9-1.yaml
crop_size:
- 250
- 250
d_model: 256
delta_cutoff: 2
detection_folders:
- TRA
distributed: false
div_upweight: 2
downscale_spatial: 1
downscale_temporal: 1
dropout: 0.01
dry: false
epochs: 50
example_images: false
feat_embed_per_dim: 8
features: regionprops
from_subfolder: false
git_commit: none
input_train:
- /root/vast/mustafa/trackastra/data/lysosomes/7-3_individual_tiffs
- /root/vast/mustafa/trackastra/data/lysosomes/8-1_individual_tiffs
- /root/vast/mustafa/trackastra/data/lysosomes/8-2_individual_tiffs
- /root/vast/mustafa/trackastra/data/lysosomes/9-2_individual_tiffs
- /root/vast/mustafa/trackastra/data/lysosomes/10-1_individual_tiffs
- /root/vast/mustafa/trackastra/data/lysosomes/10-3_individual_tiffs
- /root/vast/mustafa/trackastra/data/lysosomes/11-1_individual_tiffs
- /root/vast/mustafa/trackastra/data/lysosomes/11-2_individual_tiffs
input_val:
- /root/vast/mustafa/trackastra/data/lysosomes/7-1_individual_tiffs
- /root/vast/mustafa/trackastra/data/lysosomes/9-3_individual_tiffs
logger: tensorboard
lr: 0.0001
max_tokens: 2048
mixedp: false
model: null
n_pool_sampler: 8
name: leavout-9-1
ndim: 2
num_decoder_layers: 5
num_encoder_layers: 5
num_workers: 12
outdir: runs
pos_embed_per_dim: 32
preallocate: false
profile: false
resume: true
sanity_dist: false
seed: 3717848
slice_pct_train: &id001
- 0.0
- 1.0
slice_pct_val: *id001
spatial_pos_cutoff: 256
timestamp: true
tracking_frequency: -1
train_samples: 10000
wandb_project: trackastra
warmup_epochs: 10
weight_by_dataset: false
weight_by_ndivs: true
window: 6
